// Unit tests for the client Alpaca idempotency-key registry.
// Run: node --test src/lib/alpacaOperation.test.mjs
//
// These drive the real client key generation — begin/settle — not a
// hand-passed UUID, which is the point of #98's finding.

import test from 'node:test';
import assert from 'node:assert/strict';

const MODULE = new URL('./alpacaOperation.js', import.meta.url).href;

// A controllable sessionStorage that persists across a simulated "reload"
// (a fresh module instance) because it lives here, in the test globals.
function installStorage({ broken = false } = {}) {
  const map = new Map();
  globalThis.sessionStorage = {
    getItem(k) { if (broken) throw new Error('storage blocked'); return map.has(k) ? map.get(k) : null; },
    setItem(k, v) { if (broken) throw new Error('storage blocked'); map.set(k, String(v)); },
    removeItem(k) { if (broken) throw new Error('storage blocked'); map.delete(k); },
  };
  return map;
}

// Fresh module instance = a page reload (same sessionStorage, empty in-memory map).
let bust = 0;
const freshModule = () => import(`${MODULE}?b=${bust++}`);

const realNow = Date.now;
test.afterEach(() => { Date.now = realNow; delete globalThis.sessionStorage; });

test('a retry 16 minutes after a lost 200 keeps the same operation_id', async () => {
  installStorage();
  const { beginOperation } = await freshModule();
  const U = 'user-1';

  let t = 1_000_000_000_000;
  Date.now = () => t;

  const first = beginOperation(U, 'SPY', 30);
  assert.equal(first.isRetry, false);

  t += 16 * 60 * 1000; // 16 minutes later — past the OLD 15-min TTL
  const retry = beginOperation(U, 'SPY', 30);
  assert.equal(retry.id, first.id, 'operation_id must not be regenerated by a timer');
  assert.equal(retry.isRetry, true);
});

test('purchase A, then purchase B, then a retry of A — A keeps its id, B is distinct', async () => {
  installStorage();
  const { beginOperation } = await freshModule();
  const U = 'user-1';

  const a1 = beginOperation(U, 'SPY', 30);
  const b1 = beginOperation(U, 'SPY', 50);
  assert.notEqual(b1.id, a1.id);
  assert.equal(b1.isRetry, false, 'a different (symbol, amount) is a new operation, not a retry');

  const a2 = beginOperation(U, 'SPY', 30);
  assert.equal(a2.id, a1.id, 'starting B must not disturb the open operation for A');
  assert.equal(a2.isRetry, true);

  const b2 = beginOperation(U, 'SPY', 50);
  assert.equal(b2.id, b1.id);
});

test('settling one operation does not clear another still-open one', async () => {
  installStorage();
  const { beginOperation, settleOperation } = await freshModule();
  const U = 'user-1';

  const a = beginOperation(U, 'SPY', 30);
  const b = beginOperation(U, 'SPY', 50);

  settleOperation(U, a.id); // confirmed placement of A only

  const aNext = beginOperation(U, 'SPY', 30);
  assert.notEqual(aNext.id, a.id, 'after settle, the next purchase of the same form is genuinely new');
  assert.equal(aNext.isRetry, false);

  const bNext = beginOperation(U, 'SPY', 50);
  assert.equal(bNext.id, b.id, 'B was untouched by settling A');
  assert.equal(bNext.isRetry, true);
});

test('a retry after a page reload (fresh module, same sessionStorage) keeps the id', async () => {
  installStorage();
  const m1 = await freshModule();
  const U = 'user-1';
  const first = m1.beginOperation(U, 'SPY', 30);

  const m2 = await freshModule(); // reload
  const retry = m2.beginOperation(U, 'SPY', 30);
  assert.equal(retry.id, first.id);
  assert.equal(retry.isRetry, true);
});

test('storage unavailable — a NEW operation fails closed (no in-memory-only id a reload would lose)', async () => {
  installStorage({ broken: true });
  const { beginOperation } = await freshModule();

  const r = beginOperation('user-1', 'SPY', 30);
  assert.equal(r.id, undefined, 'must not hand back an id it cannot durably persist');
  assert.equal(r.error, 'storage_unavailable');
});

test('storage unavailable — an already-open operation is still reusable within the same page', async () => {
  // The page starts an operation while storage works, storage then breaks
  // (private-mode quirk, quota) — a retry within the same page must still
  // reconcile against the same id.
  const store = installStorage();
  const { beginOperation } = await freshModule();
  const first = beginOperation('user-1', 'SPY', 30);
  assert.ok(first.id);

  globalThis.sessionStorage.getItem = () => { throw new Error('blocked'); };
  globalThis.sessionStorage.setItem = () => { throw new Error('blocked'); };
  const retry = beginOperation('user-1', 'SPY', 30);
  assert.equal(retry.id, first.id);
  assert.equal(retry.isRetry, true);
});

// ── classifyInvestOutcome: which alpaca-invest results settle the operation
// (definite success / definite rejection) vs. leave it open for
// reconciliation (network failure, 409 "still processing", 5xx, 503).

test('classifyInvestOutcome: a confirmed placement settles', async () => {
  const { classifyInvestOutcome } = await freshModule();
  assert.equal(classifyInvestOutcome({ success: true }), 'settle');
});

test('classifyInvestOutcome: a network failure (no response) keeps the operation open', async () => {
  const { classifyInvestOutcome } = await freshModule();
  assert.equal(classifyInvestOutcome({ threw: true }), 'keep');
});

test('classifyInvestOutcome: a 409 "already submitted / still processing" keeps it open', async () => {
  const { classifyInvestOutcome } = await freshModule();
  assert.equal(classifyInvestOutcome({ httpStatus: 409, errorCode: 'This order was already submitted. Please wait a moment before retrying.' }), 'keep');
});

test('classifyInvestOutcome: a 503 order_status_unknown keeps it open', async () => {
  const { classifyInvestOutcome } = await freshModule();
  assert.equal(classifyInvestOutcome({ httpStatus: 503, errorCode: 'order_status_unknown' }), 'keep');
});

test('classifyInvestOutcome: a 500 Internal Server Error keeps it open', async () => {
  const { classifyInvestOutcome } = await freshModule();
  assert.equal(classifyInvestOutcome({ httpStatus: 500, errorCode: 'Internal Server Error' }), 'keep');
});

test('classifyInvestOutcome: alpaca_not_connected keeps it open (transient — reconnect then retry)', async () => {
  const { classifyInvestOutcome } = await freshModule();
  assert.equal(classifyInvestOutcome({ httpStatus: 400, errorCode: 'alpaca_not_connected' }), 'keep');
});

test('classifyInvestOutcome: a definite Alpaca rejection settles', async () => {
  const { classifyInvestOutcome } = await freshModule();
  assert.equal(classifyInvestOutcome({ httpStatus: 400, errorCode: 'Insufficient buying power. Available: $0.00' }), 'settle');
  assert.equal(classifyInvestOutcome({ httpStatus: 400, errorCode: 'Order failed' }), 'settle');
  assert.equal(classifyInvestOutcome({ httpStatus: 400, errorCode: 'brokerage_account_error' }), 'settle');
});

test('classifyInvestOutcome: operation_parameters_mismatch and previous_attempt_incomplete settle', async () => {
  const { classifyInvestOutcome } = await freshModule();
  assert.equal(classifyInvestOutcome({ httpStatus: 409, errorCode: 'operation_parameters_mismatch' }), 'settle');
  assert.equal(classifyInvestOutcome({ httpStatus: 200, errorCode: 'previous_attempt_incomplete', success: false }), 'settle');
});

test('classifyInvestOutcome: an unrecognised error defaults to keep-open (conservative)', async () => {
  const { classifyInvestOutcome } = await freshModule();
  assert.equal(classifyInvestOutcome({ httpStatus: 418, errorCode: 'something new' }), 'keep');
});

test('keys are per user', async () => {
  installStorage();
  const { beginOperation } = await freshModule();
  const a = beginOperation('user-1', 'SPY', 30);
  const b = beginOperation('user-2', 'SPY', 30);
  assert.notEqual(a.id, b.id);
  assert.equal(b.isRetry, false);
});

test('25h retry preserves an unresolved operation', async () => {
  installStorage();
  const m = await freshModule();
  let now = 1_000_000_000_000;
  Date.now = () => now;
  const first = m.beginOperation('user-1', 'SPY', 30);
  now += 25 * 3600_000;
  assert.equal(m.beginOperation('user-1', 'SPY', 30).id, first.id);
});

test('30 other purchases never evict unresolved A, including after reload', async () => {
  installStorage();
  const m = await freshModule();
  const first = m.beginOperation('user-1', 'SPY', 30);
  for (let n = 100; n < 130; n++) m.beginOperation('user-1', 'SPY', n);
  const reloaded = await freshModule();
  assert.equal(reloaded.beginOperation('user-1', 'SPY', 30).id, first.id);
});
