// Unit tests for the client Alpaca idempotency-key registry.
// Run: node --test src/lib/alpacaOperation.test.mjs
//
// These drive the real client key generation — begin/settle — not a
// hand-passed UUID, which is the point of #98's finding.

import test from 'node:test';
import assert from 'node:assert/strict';

const MODULE = new URL('./alpacaOperation.js', import.meta.url).href;

// A controllable sessionStorage that persists across a simulated "reload"
// (a fresh module instance) because it lives here, in the test globals.
function installStorage({ broken = false } = {}) {
  const map = new Map();
  globalThis.sessionStorage = {
    getItem(k) { if (broken) throw new Error('storage blocked'); return map.has(k) ? map.get(k) : null; },
    setItem(k, v) { if (broken) throw new Error('storage blocked'); map.set(k, String(v)); },
    removeItem(k) { if (broken) throw new Error('storage blocked'); map.delete(k); },
  };
  return map;
}

// Fresh module instance = a page reload (same sessionStorage, empty in-memory map).
let bust = 0;
const freshModule = () => import(`${MODULE}?b=${bust++}`);

const realNow = Date.now;
test.afterEach(() => { Date.now = realNow; delete globalThis.sessionStorage; });

test('a retry 16 minutes after a lost 200 keeps the same operation_id', async () => {
  installStorage();
  const { beginOperation } = await freshModule();
  const U = 'user-1';

  let t = 1_000_000_000_000;
  Date.now = () => t;

  const first = beginOperation(U, 'SPY', 30);
  assert.equal(first.isRetry, false);

  t += 16 * 60 * 1000; // 16 minutes later — past the OLD 15-min TTL
  const retry = beginOperation(U, 'SPY', 30);
  assert.equal(retry.id, first.id, 'operation_id must not be regenerated by a timer');
  assert.equal(retry.isRetry, true);
});

test('purchase A, then purchase B, then a retry of A — A keeps its id, B is distinct', async () => {
  installStorage();
  const { beginOperation } = await freshModule();
  const U = 'user-1';

  const a1 = beginOperation(U, 'SPY', 30);
  const b1 = beginOperation(U, 'SPY', 50);
  assert.notEqual(b1.id, a1.id);
  assert.equal(b1.isRetry, false, 'a different (symbol, amount) is a new operation, not a retry');

  const a2 = beginOperation(U, 'SPY', 30);
  assert.equal(a2.id, a1.id, 'starting B must not disturb the open operation for A');
  assert.equal(a2.isRetry, true);

  const b2 = beginOperation(U, 'SPY', 50);
  assert.equal(b2.id, b1.id);
});

test('settling one operation does not clear another still-open one', async () => {
  installStorage();
  const { beginOperation, settleOperation } = await freshModule();
  const U = 'user-1';

  const a = beginOperation(U, 'SPY', 30);
  const b = beginOperation(U, 'SPY', 50);

  settleOperation(U, a.id); // confirmed placement of A only

  const aNext = beginOperation(U, 'SPY', 30);
  assert.notEqual(aNext.id, a.id, 'after settle, the next purchase of the same form is genuinely new');
  assert.equal(aNext.isRetry, false);

  const bNext = beginOperation(U, 'SPY', 50);
  assert.equal(bNext.id, b.id, 'B was untouched by settling A');
  assert.equal(bNext.isRetry, true);
});

test('a retry after a page reload (fresh module, same sessionStorage) keeps the id', async () => {
  installStorage();
  const m1 = await freshModule();
  const U = 'user-1';
  const first = m1.beginOperation(U, 'SPY', 30);

  const m2 = await freshModule(); // reload
  const retry = m2.beginOperation(U, 'SPY', 30);
  assert.equal(retry.id, first.id);
  assert.equal(retry.isRetry, true);
});

test('storage unavailable — retry still reuses the id within the page; settle still ends it', async () => {
  installStorage({ broken: true });
  const { beginOperation, settleOperation } = await freshModule();
  const U = 'user-1';

  const first = beginOperation(U, 'SPY', 30);
  const retry = beginOperation(U, 'SPY', 30);
  assert.equal(retry.id, first.id, 'in-memory fallback must keep the key stable when sessionStorage throws');
  assert.equal(retry.isRetry, true);

  settleOperation(U, first.id);
  const afterSettle = beginOperation(U, 'SPY', 30);
  assert.notEqual(afterSettle.id, first.id);
});

test('keys are per user', async () => {
  installStorage();
  const { beginOperation } = await freshModule();
  const a = beginOperation('user-1', 'SPY', 30);
  const b = beginOperation('user-2', 'SPY', 30);
  assert.notEqual(a.id, b.id);
  assert.equal(b.isRetry, false);
});
